version: 2 # use version 2.0 of CircleCI

jobs: # a basic unit of work in a run
  build: # runs not using `Workflows` must have a `build` job as entry point
    docker:
      - image: debian:stretch
    steps: # a series of commands to run
      - checkout
      - run:
          name: Sync submodule
          command: 'git submodule update --init --remote --recursive'
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMake
          command: 'apt-get install cmake'
      - run:
          name: Install Boost
          command: 'apt-get install boost'
      - run:
          name: Install FFmpeg
          command: 'apt-get install ffmpeg'
      - run:
          name: Install spdlog
          command: 'apt-get install spdlog'
      - run:
          name: Create build files
          command: 'mkdir build ; cd build ; cmake ..'
      - run:
          name: Compile
          command: 'make -j2'